### PR TITLE
no auto bower install

### PR DESCRIPTION
**Pull request by kompolom**

### CODE REVIEW

**Comment by awinogradov** [comment]
Why is it a problem?

**Comment by tadatuta** [comment]
@awinogradov 
> Why is it a problem?

it's a library which can be used on a project without bower (where all the deps are installed with `npm` for example). library should not dictate anything.

**Comment by tadatuta** [comment]
@kompolom this is a useful PR but libs should be installed in `travis` environment to run tests

**Comment by belozer** [comment]
@kompolom ping

**Comment by kompolom** [comment]
@awinogradov @tadatuta fixed! Now we run `npm run deps` before travis starts specs.

**Comment by belozer** [comment]
@awinogradov ping

**Pull request merged**
